"""
High level OCR service that exposes training + inference capabilities.
Provides a reusable module for the Streamlit app or any other integration.
"""

from __future__ import annotations

import io
import tempfile
import zipfile
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import cv2
import numpy as np
import torch
from PIL import Image

from .models import CRNN
from .pdf_utils import pdf_to_images, create_searchable_pdf
from .vietnamese_diacritics_expanded import VIETNAMESE_CORRECTIONS_EXPANDED
try:
    from .vietnamese_diacritics_expanded_auto import VIETNAMESE_CORRECTIONS_EXPANDED as VIETNAMESE_CORRECTIONS_EXPANDED_AUTO
except Exception:
    VIETNAMESE_CORRECTIONS_EXPANDED_AUTO = {}


# Vietnamese diacritic recovery dictionary (base + expanded)
VIETNAMESE_CORRECTIONS = {
    # Common undiacritized words → diacritized forms
    'cong': ['công'],
    'viec': ['việc', 'viêc'],
    'mo': ['mô'],
    'ta': ['tả'],
    'noilam': ['nơi làm', 'nơi làm'],
    'hoc': ['học'],
    'khach': ['khách'],
    'phan': ['phần'],
    'kinh': ['kinh'],
    'san': ['sản'],
    'da': ['đã', 'đa'],
    'de': ['để', 'dễ'],
    'dau': ['dấu'],
    'tien': ['tiền'],
    'man': ['màn'],
    'tay': ['tay'],
    'trai': ['trái'],
    'qua': ['qua'],
    'theo': ['theo'],
    'loai': ['loại'],
    'thi': ['thì', 'thi'],
    'muc': ['mục'],
    'thao': ['thao'],
    'ngay': ['ngày'],
    'nhung': ['nhưng'],
    'ca': ['cả'],
    'toan': ['toàn'],
    'may': ['máy'],
    'mang': ['mạng'],
    'phan': ['phần'],
    'chuc': ['chức'],
    'uat': ['uất'],
    'tai': ['tài'],
    'chuyen': ['chuyên'],
    'nhan': ['nhân'],
    'tro': ['trở'],
    'len': ['lên'],
    'huong': ['hướng'],
    'san': ['sản'],
    'phu': ['phụ'],
    'bien': ['biến'],
    'tuoi': ['tuổi'],
    'than': ['thần'],
    'pho': ['phổ'],
    'chung': ['chùng'],
}

# Merge expanded diacritics from synthetic vocabulary
VIETNAMESE_CORRECTIONS.update(VIETNAMESE_CORRECTIONS_EXPANDED)
VIETNAMESE_CORRECTIONS.update(VIETNAMESE_CORRECTIONS_EXPANDED_AUTO)

# Try to load additional vocabulary-based diacritics from tools (generated by extract_vocabulary)
try:
    import json
    extra_vocab_path = Path(__file__).parent.parent / 'tools' / 'vocab_vietnamese_diacritics.json'
    if extra_vocab_path.exists():
        with extra_vocab_path.open('r', encoding='utf-8') as fh:
            extra = json.load(fh)
            # extra keys may be already diacritized; we map lowercased undiacritized forms to first suggestion
            for k, v in extra.items():
                # normalize key to undiacritized ascii for matching (simple lowercasing)
                try:
                    und = k.lower()
                    if und not in VIETNAMESE_CORRECTIONS and v:
                        # store first suggestion
                        VIETNAMESE_CORRECTIONS[und] = [v[0]]
                except Exception:
                    continue
except Exception:
    pass
def restore_vietnamese_diacritics(text: str) -> str:
    """
    Restore Vietnamese diacritics on undiacritized text.
    Uses a simple dictionary-based approach for common words.
    """
    if not text:
        return text
    
    # Remove spaces and convert to lowercase for matching
    words = text.split()
    corrected = []
    
    for word in words:
        # Try to find exact match first
        lower_word = word.lower()
        
        # Look for partial matches (undiacritized form)
        best_match = None
        for undiacritized, diacritized_forms in VIETNAMESE_CORRECTIONS.items():
            if lower_word == undiacritized or lower_word.startswith(undiacritized):
                best_match = diacritized_forms[0]  # Take first (most common) form
                break
        
        if best_match:
            # Preserve original casing if first letter was uppercase
            if word and word[0].isupper():
                corrected.append(best_match[0].upper() + best_match[1:])
            else:
                corrected.append(best_match)
        else:
            corrected.append(word)
    
    return ' '.join(corrected)

try:
    from .training import TrainingConfig, train_crnn_model
except Exception:  # training module optional — provide informative stubs
    from dataclasses import dataclass
    from typing import Optional

    @dataclass
    class TrainingConfig:
        dataset_root: str = ""
        train_split: str = "train_set.txt"
        val_split: str = "validation_set.txt"
        epochs: int = 5
        batch_size: int = 8
        lr: float = 1e-4
        save_path: Optional[str] = None
        use_synthetic: bool = True
        synthetic_size: int = 0
        num_workers: int = 0
        device: Optional[str] = None

    def train_crnn_model(cfg, progress_callback=None):
        raise RuntimeError(
            "Training helper 'src.training' not available.\n"
            "To train, either add 'src/training.py' or run the provided training script 'train_crnn.py' from project root."
        )
from .utils import (
    adaptive_binarize,
    clahe_equalize,
    denoise,
    normalize_for_model,
    pad_width,
    resize_keep_aspect,
    robust_deskew,
)
from .dataset import VOCAB
from .enhancer import ImageEnhancer
from .text_detector import TextDetector
from .language_model import VietnameseLanguageModel
from .postprocessor_advanced import VietnamesePostprocessor

try:
    import pytesseract
except Exception:  # pragma: no cover - optional dependency
    pytesseract = None

try:
    import easyocr

    _easyocr_reader = None
except Exception:  # pragma: no cover - optional dependency
    easyocr = None
    _easyocr_reader = None


def _pil_to_gray(image: Image.Image) -> np.ndarray:
    if image.mode != "L":
        image = image.convert("L")
    return np.array(image)


def _to_tensor(gray_img: np.ndarray, target_h: int = 32, max_w: int = 512) -> torch.Tensor:
    resized = resize_keep_aspect(gray_img, height=target_h, max_width=max_w)
    normalized = normalize_for_model(resized)
    padded = pad_width((255 - (normalized * 255)).astype(np.uint8), max_w)
    normalized = (255 - padded).astype(np.float32) / 255.0
    return torch.from_numpy(normalized).unsqueeze(0).unsqueeze(0)


def _enhance(gray: np.ndarray) -> np.ndarray:
    """Enhanced image preprocessing with advanced techniques"""
    # Use new enhancer module for better quality
    enhanced = ImageEnhancer.enhance_image(gray)
    return enhanced


@dataclass
class OCRResult:
    text: str
    source: Optional[str]
    candidates: List[Dict[str, str]]
    success: bool
    pages: int = 1
    details: Optional[Dict] = None


class OCRService:
    """
    Unified interface for training + OCR inference.
    Can be reused by the web UI or by external modules.
    """

    def __init__(
        self,
        model_path: str = "crnn_vnondb.pth",  # 🎯 Changed from crnn_best.pth to use VNOnDB-trained model
        device: Optional[str] = None,
        lazy: bool = False,
    ) -> None:
        self.model_path = Path(model_path)
        self.device = torch.device(
            device
            if device
            else ("cuda" if torch.cuda.is_available() else "cpu")
        )
        self.model: Optional[CRNN] = None
        self.vocab = VOCAB
        self.has_tesseract = pytesseract is not None
        self.has_easyocr = easyocr is not None

        # Initialize enhancement and detection modules
        self.enhancer = ImageEnhancer()
        self.detector = TextDetector()
        self.language_model = VietnameseLanguageModel()
        self.postprocessor = VietnamesePostprocessor(diacritic_map=VIETNAMESE_CORRECTIONS)

        if not lazy:
            self.load_model()

    # ------------------------------------------------------------------ #
    # Model handling
    # ------------------------------------------------------------------ #
    def load_model(self) -> None:
        if not self.model_path.exists():
            self.model = None
            return

        state = torch.load(self.model_path, map_location=self.device)
        state_dict = state["model"] if "model" in state else state
        model = CRNN(num_classes=len(self.vocab), in_channels=1, rnn_hidden=256)
        model.load_state_dict(state_dict, strict=False)
        model.eval()
        self.model = model.to(self.device)

    # ------------------------------------------------------------------ #
    # Inference helpers
    # ------------------------------------------------------------------ #
    def _decode_ctc(self, probs: torch.Tensor) -> str:
        seq = probs.argmax(-1)[0].cpu().numpy().tolist()
        result = []
        prev = None
        for idx in seq:
            if idx == 0:
                prev = idx
                continue
            if idx == prev:
                continue
            if idx < len(self.vocab):
                result.append(self.vocab[idx])
            prev = idx
        return "".join(result).strip()

    def _run_crnn(self, image: Image.Image) -> Optional[Dict[str, str]]:
        if self.model is None:
            return None

        gray = _pil_to_gray(image)
        gray = _enhance(gray)
        tensor = _to_tensor(gray)
        tensor = tensor.to(self.device)
        with torch.no_grad():
            output = self.model(tensor)
            probs = output.softmax(-1)
        text = self._decode_ctc(probs)
        if not text:
            return None
        return {"source": "crnn", "text": text, "confidence": 0.65}

    def _run_tesseract(self, image: Image.Image) -> Optional[Dict[str, str]]:
        if not self.has_tesseract:
            return None
        try:
            try:
                res = pytesseract.image_to_data(image, lang="vie", output_type=pytesseract.Output.DICT)
            except Exception:
                res = pytesseract.image_to_data(image, output_type=pytesseract.Output.DICT)
            text = " ".join([w for w in res["text"] if w.strip()])
            if not text.strip():
                return None
            confs = [int(c) for c in res.get("conf", []) if c not in ("-1", None)]
            confidence = float(sum(confs) / len(confs)) / 100 if confs else 0.75
            return {"source": "tesseract", "text": text.strip(), "confidence": confidence}
        except Exception:
            return None

    def _run_tesseract_detailed(self, image: Image.Image) -> List[Dict]:
        """Return list of words with bbox and confidence from Tesseract (if available)."""
        out = []
        if not self.has_tesseract:
            return out
        try:
            try:
                res = pytesseract.image_to_data(image, lang="vie", output_type=pytesseract.Output.DICT)
            except Exception:
                res = pytesseract.image_to_data(image, output_type=pytesseract.Output.DICT)
            n = len(res.get('text', []))
            for i in range(n):
                w = res['text'][i].strip()
                if not w:
                    continue
                left = int(res['left'][i])
                top = int(res['top'][i])
                width = int(res['width'][i])
                height = int(res['height'][i])
                conf = res['conf'][i]
                try:
                    conf_f = float(conf)/100.0
                except Exception:
                    try:
                        conf_f = (int(conf) if conf not in ('-1', '') else 75)/100.0
                    except Exception:
                        conf_f = 0.75
                out.append({'text': w, 'bbox': (left, top, left+width, top+height), 'confidence': conf_f, 'source': 'tesseract'})
        except Exception:
            return out
        return out

    def _run_easyocr(self, image: Image.Image) -> Optional[Dict[str, str]]:
        global _easyocr_reader
        if not self.has_easyocr:
            return None
        if _easyocr_reader is None:
            _easyocr_reader = easyocr.Reader(["vi", "en"], gpu=False)
        arr = np.array(image.convert("RGB"))
        texts = _easyocr_reader.readtext(arr, detail=0, paragraph=True)
        merged = " ".join([t.strip() for t in texts if t and t.strip()])
        if not merged:
            return None
        return {"source": "easyocr", "text": merged.strip(), "confidence": 0.7}

    def _run_easyocr_detailed(self, image: Image.Image) -> List[Dict]:
        """Return list of words with bbox and confidence from EasyOCR (if available)."""
        out = []
        global _easyocr_reader
        if not self.has_easyocr:
            return out
        if _easyocr_reader is None:
            _easyocr_reader = easyocr.Reader(["vi", "en"], gpu=False)
        arr = np.array(image.convert("RGB"))
        try:
            raw = _easyocr_reader.readtext(arr, detail=1)
            for item in raw:
                bbox_pts, txt, conf = item
                xs = [p[0] for p in bbox_pts]
                ys = [p[1] for p in bbox_pts]
                x1, x2 = int(min(xs)), int(max(xs))
                y1, y2 = int(min(ys)), int(max(ys))
                out.append({'text': txt.strip(), 'bbox': (x1, y1, x2, y2), 'confidence': float(conf), 'source': 'easyocr'})
        except Exception:
            return out
        return out

    def export_searchable_pdf(self, file_bytes: bytes, output_path: str, dpi: int = 150) -> Tuple[bool, str]:
        """Convert PDF (or image) to searchable PDF with text layer using OCR word boxes.
        Returns (success, message).
        """
        images, err = pdf_to_images(file_bytes, dpi=dpi)
        if err:
            return False, err

        words_per_page = []
        for img in images:
            # prefer tesseract detailed boxes; fallback to easyocr
            tess_words = self._run_tesseract_detailed(img) if self.has_tesseract else []
            easy_words = self._run_easyocr_detailed(img) if self.has_easyocr else []

            if tess_words:
                words = tess_words
            elif easy_words:
                words = easy_words
            else:
                # as fallback, run full-image recognition and place text at top-left
                res = self.recognize_image(img)
                txt = res.text or ""
                if txt:
                    w_px, h_px = img.size
                    words = [{'text': txt, 'bbox': (10, 10, min(200, w_px-10), 30), 'confidence': 0.5, 'source': 'crnn'}]
                else:
                    words = []

            words_per_page.append(words)

        # create searchable PDF
        try:
            create_searchable_pdf(output_path, images, words_per_page, dpi=dpi)
            return True, "OK"
        except Exception as e:
            return False, str(e)

    @staticmethod
    def _select_best(candidates: List[Dict[str, str]]) -> Optional[Dict[str, str]]:
        if not candidates:
            return None
        return sorted(
            candidates,
            key=lambda item: (item.get("confidence", 0), len(item.get("text", ""))),
            reverse=True,
        )[0]

    def recognize_image(
        self,
        image: Image.Image,
        detect_printed: bool = True,
        detect_handwritten: bool = True,
        use_easyocr: bool = True,
        use_enhancement: bool = True,
        use_language_model: bool = True,
    ) -> OCRResult:
        candidates: List[Dict[str, str]] = []

        # Step 1: Text detection to find text regions
        if hasattr(self, 'detector'):
            detected_regions = self.detector.detect_text_regions(image)
            if detected_regions:
                # Process each detected region
                region_texts = []
                for region in detected_regions:
                    region_img = image.crop(region['bbox'])
                    region_result = self._recognize_single_region(
                        region_img, detect_printed, detect_handwritten, use_easyocr, use_enhancement
                    )
                    if region_result and region_result.get("text"):
                        region_texts.append(region_result["text"])

                if region_texts:
                    combined_text = " ".join(region_texts)
                    candidates.append({
                        "source": "detector+multi_region",
                        "text": combined_text,
                        "confidence": 0.8
                    })

        # Step 2: Full image recognition as fallback
        full_result = self._recognize_single_region(
            image, detect_printed, detect_handwritten, use_easyocr, use_enhancement
        )
        if full_result:
            candidates.append(full_result)

        best = self._select_best(candidates)
        raw_text = best.get("text") if best else ""

        # Step 3: Language model correction
        if raw_text and use_language_model and hasattr(self, 'language_model'):
            corrected_text = self.language_model.correct_text(raw_text)
            if corrected_text != raw_text:
                candidates.append({
                    "source": "language_model_corrected",
                    "text": corrected_text,
                    "confidence": 0.9
                })
                best = self._select_best(candidates)

        text = best.get("text") if best else ""
        # Step 4: Apply advanced postprocessing (OCR typo fix + word merge + diacritic restoration)
        if text and hasattr(self, 'postprocessor'):
            text = self.postprocessor.postprocess(text)
        # Step 5: Apply Vietnamese diacritic recovery (dictionary fallback)
        text = restore_vietnamese_diacritics(text)
        return OCRResult(
            text=text,
            source=best.get("source") if best else None,
            candidates=candidates,
            success=bool(text.strip()),
        )

    def _recognize_single_region(
        self,
        image: Image.Image,
        detect_printed: bool,
        detect_handwritten: bool,
        use_easyocr: bool,
        use_enhancement: bool
    ) -> Optional[Dict[str, str]]:
        """Recognize text in a single image region"""
        candidates = []

        # Apply enhancement if requested
        if use_enhancement:
            gray = _pil_to_gray(image)
            enhanced_gray = _enhance(gray)
            enhanced_image = Image.fromarray(enhanced_gray)
        else:
            enhanced_image = image

        # Run different OCR engines
        if detect_printed:
            tess = self._run_tesseract(enhanced_image)
            if tess:
                candidates.append(tess)

        if use_easyocr:
            easy = self._run_easyocr(enhanced_image)
            if easy:
                candidates.append(easy)

        if detect_handwritten:
            crnn_result = self._run_crnn(enhanced_image)
            if crnn_result:
                candidates.append(crnn_result)

        return self._select_best(candidates)

    # ------------------------------------------------------------------ #
    # Fusion helpers (word-level voting & engine fusion)
    # ------------------------------------------------------------------ #
    def _align_words_to_ref(self, ref_words: List[str], other_words: List[str]) -> List[Optional[str]]:
        """Align `other_words` to `ref_words` using SequenceMatcher on tokens.
        Returns a list with same length as ref_words where elements are the corresponding
        word from other_words or None if missing.
        """
        import difflib

        sm = difflib.SequenceMatcher(a=ref_words, b=other_words)
        aligned = []
        for tag, i1, i2, j1, j2 in sm.get_opcodes():
            if tag == 'equal':
                aligned.extend(other_words[j1:j2])
            elif tag == 'replace':
                # map as many as possible, pad with None
                len_ref = i2 - i1
                len_other = j2 - j1
                for k in range(len_ref):
                    if j1 + k < j2:
                        aligned.append(other_words[j1 + k])
                    else:
                        aligned.append(None)
            elif tag == 'delete':
                # ref has words that other doesn't
                for _ in range(i2 - i1):
                    aligned.append(None)
            elif tag == 'insert':
                # other has extra words; attach them to previous ref position if exists, else skip
                if aligned:
                    # append the insert as additional token to last aligned entry
                    prev = aligned[-1]
                    # if previous is None, replace with inserted first, else keep prev
                    if prev is None:
                        aligned[-1] = other_words[j1]
                # otherwise ignore standalone inserts
        # Ensure length matches
        if len(aligned) < len(ref_words):
            aligned.extend([None] * (len(ref_words) - len(aligned)))
        return aligned[: len(ref_words)]

    def _fuse_texts_word_level(self, candidates: List[Dict[str, str]]) -> Dict[str, object]:
        """Fuse multiple candidate texts (from different engines) using word-level voting.
        Each candidate is a dict with keys: 'text', 'source', 'confidence'.
        Returns dict with 'text' and 'details' mapping position->chosen source.
        """
        # Prepare list of tokenized word lists
        token_lists = []
        confidences = []
        sources = []
        for c in candidates:
            txt = (c.get('text') or '').strip()
            words = txt.split()
            token_lists.append(words)
            confidences.append(float(c.get('confidence', 0.5)))
            sources.append(c.get('source', 'unknown'))

        if not token_lists:
            return {'text': '', 'details': {}}

        # Choose reference as the longest token list
        ref_idx = max(range(len(token_lists)), key=lambda i: len(token_lists[i]))
        ref_words = token_lists[ref_idx]

        aligned_candidates = []
        for words in token_lists:
            aligned = self._align_words_to_ref(ref_words, words)
            aligned_candidates.append(aligned)

        chosen_words = []
        details = {}
        for pos in range(len(ref_words)):
            votes: Dict[str, int] = {}
            vote_sources: Dict[str, List[int]] = {}
            for ci, aligned in enumerate(aligned_candidates):
                w = aligned[pos] if pos < len(aligned) else None
                if w is None:
                    continue
                votes[w] = votes.get(w, 0) + 1
                vote_sources.setdefault(w, []).append(ci)

            if votes:
                # Choose most-voted word, tie-breaker by highest average confidence among voters
                best_word, best_count = None, -1
                best_score = -1.0
                for w, count in votes.items():
                    idxs = vote_sources[w]
                    avg_conf = sum(confidences[i] for i in idxs) / len(idxs)
                    if count > best_count or (count == best_count and avg_conf > best_score):
                        best_word = w
                        best_count = count
                        best_score = avg_conf

                # record chosen and source (take first source with that word and highest conf)
                source_candidates = vote_sources.get(best_word, [])
                best_src_idx = max(source_candidates, key=lambda i: confidences[i])
                chosen_words.append(best_word)
                details[pos] = {'word': best_word, 'source': sources[best_src_idx], 'confidence': best_score}
            else:
                chosen_words.append(ref_words[pos])
                details[pos] = {'word': ref_words[pos], 'source': sources[ref_idx], 'confidence': confidences[ref_idx]}

        fused_text = ' '.join(chosen_words)
        return {'text': fused_text, 'details': details}

    def _align_chars_to_ref(self, ref: str, other: str) -> List[Optional[str]]:
        """Align characters from `other` to `ref` and return a list with same length as ref
        where elements are the corresponding character from other or None if missing.
        Uses difflib.SequenceMatcher on characters.
        """
        import difflib

        a = list(ref)
        b = list(other)
        sm = difflib.SequenceMatcher(a=a, b=b)
        aligned: List[Optional[str]] = []
        for tag, i1, i2, j1, j2 in sm.get_opcodes():
            if tag == 'equal':
                aligned.extend(b[j1:j2])
            elif tag == 'replace':
                len_ref = i2 - i1
                for k in range(len_ref):
                    if j1 + k < j2:
                        aligned.append(b[j1 + k])
                    else:
                        aligned.append(None)
            elif tag == 'delete':
                for _ in range(i2 - i1):
                    aligned.append(None)
            elif tag == 'insert':
                # attach insert to previous aligned char if possible
                if aligned and j1 < j2:
                    if aligned[-1] is None:
                        aligned[-1] = b[j1]
        if len(aligned) < len(a):
            aligned.extend([None] * (len(a) - len(aligned)))
        return aligned[: len(a)]

    def _fuse_texts_char_level(self, candidates: List[Dict[str, str]]) -> Dict[str, object]:
        """Fuse candidate texts at character level using confidence-weighted voting.
        Returns {'text': fused_text, 'details': {pos: {char, source, confidence}}}
        """
        texts = [ (c.get('text') or '').strip() for c in candidates ]
        confs = [ float(c.get('confidence', 0.5)) for c in candidates ]
        sources = [ c.get('source', 'unknown') for c in candidates ]

        if not texts:
            return {'text': '', 'details': {}}

        ref_idx = max(range(len(texts)), key=lambda i: len(texts[i]))
        ref = texts[ref_idx]

        aligned_chars = [ self._align_chars_to_ref(ref, t) for t in texts ]

        chosen = []
        details = {}
        for pos in range(len(ref)):
            votes: Dict[str, float] = {}
            vote_sources: Dict[str, List[int]] = {}
            for ci, aligned in enumerate(aligned_chars):
                ch = aligned[pos] if pos < len(aligned) else None
                if ch is None:
                    continue
                votes[ch] = votes.get(ch, 0.0) + confs[ci]
                vote_sources.setdefault(ch, []).append(ci)

            if votes:
                best_char = max(votes.items(), key=lambda kv: (kv[1], kv[0]))[0]
                idxs = vote_sources.get(best_char, [])
                avg_conf = sum(confs[i] for i in idxs)/len(idxs) if idxs else 0.0
                best_src_idx = max(idxs, key=lambda i: confs[i]) if idxs else ref_idx
                chosen.append(best_char)
                details[pos] = {'char': best_char, 'source': sources[best_src_idx], 'confidence': avg_conf}
            else:
                chosen.append(ref[pos])
                details[pos] = {'char': ref[pos], 'source': sources[ref_idx], 'confidence': confs[ref_idx]}

        return {'text': ''.join(chosen), 'details': details}

    def recognize_image_fused(
        self,
        image: Image.Image,
        use_easyocr: bool = True,
        use_tesseract: bool = True,
        use_crnn: bool = True,
        char_level: bool = False,
    ) -> OCRResult:
        """Run all available engines and fuse results (word-level voting).
        Useful to combine handwriting CRNN + printed OCR + EasyOCR/Tesseract.
        """
        candidates = []

        # Preprocess/enhance image
        gray = _pil_to_gray(image)
        enhanced_gray = _enhance(gray)
        enhanced_image = Image.fromarray(enhanced_gray)

        if use_crnn:
            crnn_res = self._run_crnn(enhanced_image)
            if crnn_res:
                candidates.append(crnn_res)

        if use_tesseract:
            tess_res = self._run_tesseract(enhanced_image)
            if tess_res:
                candidates.append(tess_res)

        if use_easyocr:
            easy_res = self._run_easyocr(enhanced_image)
            if easy_res:
                candidates.append(easy_res)

        fused = self._fuse_texts_word_level(candidates)
        if char_level:
            fused = self._fuse_texts_char_level(candidates)

        # Build returned OCRResult
        # Apply advanced postprocessing
        fused_text = fused['text']
        if hasattr(self, 'postprocessor'):
            fused_text = self.postprocessor.postprocess(fused_text)
        # Apply Vietnamese diacritic recovery
        fused_text = restore_vietnamese_diacritics(fused_text)
        return OCRResult(
            text=fused_text,
            source='fusion',
            candidates=candidates,
            success=bool(fused['text'].strip()),
            pages=1,
            details=fused.get('details', None),
        )

    def recognize_document(
        self,
        file_bytes: bytes,
        filename: Optional[str] = None,
        detect_printed: bool = True,
        detect_handwritten: bool = True,
        use_easyocr: bool = True,
    ) -> OCRResult:
        name = (filename or "").lower()
        if name.endswith(".pdf"):
            images, error = pdf_to_images(file_bytes)
            if error:
                return OCRResult(text=error, source=None, candidates=[], success=False)
        else:
            try:
                image = Image.open(io.BytesIO(file_bytes))
            except Exception as exc:
                return OCRResult(text=f"Unsupported file: {exc}", source=None, candidates=[], success=False)
            images = [image]

        texts = []
        all_candidates: List[Dict[str, str]] = []
        for image in images:
            result = self.recognize_image(
                image,
                detect_printed=detect_printed,
                detect_handwritten=detect_handwritten,
                use_easyocr=use_easyocr,
            )
            if result.success:
                texts.append(result.text)
            all_candidates.extend(result.candidates)

        merged = "\n".join(texts).strip()
        best = self._select_best(all_candidates)
        return OCRResult(
            text=merged if merged else (best["text"] if best else ""),
            source=best.get("source") if best else None,
            candidates=all_candidates,
            success=bool(merged or best),
            pages=len(images),
        )

    # ------------------------------------------------------------------ #
    # Training helpers
    # ------------------------------------------------------------------ #
    def train_on_directory(
        self,
        dataset_root: str,
        epochs: int = 5,
        batch_size: int = 8,
        lr: float = 1e-4,
        use_synthetic: bool = True,
        progress_callback=None,
        save_path: Optional[str] = None,
        train_split: str = "train_set.txt",
        val_split: str = "validation_set.txt",
    ) -> Dict[str, float]:
        cfg = TrainingConfig(
            dataset_root=dataset_root,
            train_split=train_split,
            val_split=val_split,
            epochs=epochs,
            batch_size=batch_size,
            lr=lr,
            save_path=save_path or str(self.model_path),
            use_synthetic=use_synthetic,
        )
        result = train_crnn_model(cfg, progress_callback=progress_callback)
        self.load_model()
        return result

    def train_from_zip(
        self,
        zip_bytes: bytes,
        epochs: int = 3,
        batch_size: int = 4,
        lr: float = 1e-4,
        use_synthetic: bool = True,
        progress_callback=None,
        save_path: Optional[str] = None,
    ) -> Dict[str, float]:
        with tempfile.TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)
            with zipfile.ZipFile(io.BytesIO(zip_bytes)) as archive:
                archive.extractall(tmp_path)

            images_dir = None
            root_dir = None
            labels_file = None
            train_file = None
            val_file = None
            for path in tmp_path.rglob("*"):
                if path.is_dir() and path.name.lower() == "images":
                    images_dir = path
                    root_dir = path.parent
                if path.is_file():
                    name = path.name.lower()
                    if name == "labels.txt":
                        labels_file = path
                    elif name == "train_set.txt":
                        train_file = path
                    elif name == "validation_set.txt":
                        val_file = path

            if images_dir is None:
                raise ValueError("Zip must contain an images/ folder")

            if (train_file is None or val_file is None) and labels_file is None:
                raise ValueError("Zip must include labels.txt or train/validation splits")

            if root_dir is None:
                root_dir = images_dir.parent

            if train_file is None or val_file is None:
                lines = [line.strip() for line in labels_file.read_text(encoding="utf-8").splitlines() if line.strip()]
                if not lines:
                    raise ValueError("labels.txt is empty")
                split_idx = max(1, int(len(lines) * 0.9))
                train_lines = lines[:split_idx]
                val_lines = lines[split_idx:] or lines[-1:]
                train_file = root_dir / "train_set.txt"
                val_file = root_dir / "validation_set.txt"
                train_file.write_text("\n".join(train_lines), encoding="utf-8")
                val_file.write_text("\n".join(val_lines), encoding="utf-8")

            dataset_root = str(root_dir)
            return self.train_on_directory(
                dataset_root=dataset_root,
                epochs=epochs,
                batch_size=batch_size,
                lr=lr,
                use_synthetic=use_synthetic,
                progress_callback=progress_callback,
                save_path=save_path,
                train_split=train_file.name,
                val_split=val_file.name,
            )


__all__ = ["OCRService", "OCRResult"]

