VIETNAMESE_CORRECTIONS_EXPANDED = {
    'bao': ['bảo'],
    'cap': ['cấp'],
    'chao': ['chào'],
    'chung': ['chứng'],
    'cong': ['công'],
    'du': ['dữ'],
    'ha': ['hà'],
    'he': ['hệ'],
    'ho': ['hỗ'],
    'hoan': ['hoàn'],
    'hoang': ['hoàng'],
    'hoc': ['học'],
    'lieu': ['liệu'],
    'ly': ['lý'],
    'mang': ['mạng'],
    'may': ['máy'],
    'nam': ['năm'],
    'nang': ['nâng'],
    'nghe': ['nghệ'],
    'nhan': ['nhận', 'nhân'],
    'noi': ['nội'],
    'pha': ['phả'],
    'phieu': ['phiếu'],
    'phong': ['phỏng'],
    'quan': ['quản'],
    'so': ['số'],
    'thang': ['tháng'],
    'thanh': ['thành'],
    'thong': ['thống', 'thông'],
    'tinh': ['tính'],
    'tri': ['trì'],
    'tro': ['trợ'],
    'van': ['vấn'],
    'viec': ['việc'],
    'vien': ['viên', 'viện'],
    'xet': ['xét'],
    'đong': ['đông'],
    'đuong': ['đường'],
}
